import AuthProfile from './AuthProfile'
import SharedLayout from './SharedLayout'
import AddPost from './AddPost'
import AllPost from './AllPost'
import UnauthAccount from './UnauthAccount'
import UpdateProfile from './UpdateProfile'
import Discover from './Discover'
import SinglePost from './SinglePost'
import UpdatePost from './UpdatePost'
import Explore from './Explore'
export { AuthProfile, SharedLayout, AddPost, AllPost, UnauthAccount, UpdateProfile, Discover, SinglePost, UpdatePost, Explore }
