export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const LOGOUT_USER = 'LOGOUT_USER'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const GET_SINGLEUSER_BEGIN = 'GET_SINGLEUSER_BEGIN'
export const GET_SINGLEUSER_SUCCESS = 'GET_SINGLEUSER_SUCCESS'
export const GET_SINGLEUSER_ERROR = 'GET_SINGLEUSER_ERROR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_POST_BEGIN = 'CREATE_POST_BEGIN'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

export const UPDATE_POST_BEGIN = 'UPDATE_POST_BEGIN'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'

export const DELETE_POST_BEGIN = 'DELETE_POST_BEGIN'

export const GET_POSTS_BEGIN = 'GET_POSTS_BEGIN'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR'

export const GET_UNAUTHPOSTS_BEGIN = 'GET_UNAUTHPOSTS_BEGIN'
export const GET_UNAUTHPOSTS_SUCCESS = 'GET_UNAUTHPOSTS_SUCCESS'
export const GET_UNAUTHPOSTS_ERROR = 'GET_UNAUTHPOSTS_ERROR'

export const GET_SINGLEPOST_BEGIN = 'GET_SINGLEPOST_BEGIN'
export const GET_SINGLEPOST_SUCCESS = 'GET_SINGLEPOST_SUCCESS'
export const GET_SINGLEPOST_ERROR = 'GET_SINGLEPOST_ERROR'

export const LIKE_POST_BEGIN = 'LIKE_POST_BEGIN'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_ERROR = 'LIKE_POST_ERROR'

export const UNLIKE_POST_BEGIN = 'UNLIKE_POST_BEGIN'
export const UNLIKE_POST_SUCCESS = 'UNLIKE_POST_SUCCESS'
export const UNLIKE_POST_ERROR = 'UNLIKE_POST_ERROR'

export const GET_DISCOVER_BEGIN = 'GET_DISCOVER_BEGIN'
export const GET_DISCOVER_SUCCESS = 'GET_DISCOVER_SUCCESS'
export const GET_DISCOVER_ERROR = 'GET_DISCOVER_ERROR'

export const FOLLOW_USER_BEGIN = 'FOLLOW_USER_BEGIN'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_ERROR = 'FOLLOW_USER_ERROR'

export const UNFOLLOW_USER_BEGIN = 'FOLLOW_USER_BEGIN'
export const UNFOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const UNFOLLOW_USER_ERROR = 'FOLLOW_USER_ERROR'

export const SET_ADD_COMMENT = 'SET_ADD_COMMENT '

export const CREATE_COMMENT_BEGIN = 'CREATE_COMMENT_BEGIN'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR'

export const OPEN_SUBMENU = 'OPEN_SUBMENU'
export const CLOSE_SUBMENU = 'CLOSE_SUBMENU'

export const SEARCH_USER_BEGIN = 'SEARCH_USER_BEGIN'
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS'
export const SEARCH_USER_ERROR = 'SEARCH_USER_ERROR'

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

export const CHANGE_PAGE = 'CHANGE_PAGE';


